const data = {
  products: [
    {
      _id: "1",
      name: "Tie Dye T-Shirt for Women/Girls",
      category: "T-Shirts",
      image: "https://m.media-amazon.com/images/I/515WK8bKtFL._UL1196_.jpg",
      price: 299 - 349,
      brand: "JUNEBEERY",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Campus Sutra Women's Plain Jacket",
      category: "Jacket",
      image: "https://m.media-amazon.com/images/I/71eeBR8ka0L._UL1500_.jpg",
      price: 399 - 1219,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "SIRIL Women's Crepe Slim Fit Digital Printed Top",
      category: "Shirts",
      image: "https://m.media-amazon.com/images/I/81d1WtX6jkL._UL1500_.jpg",
      price: 299 - 349,
      brand: "SIRIL",
      rating: 4.0,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Aahwan Women's & Girl's Solid Full Sleeve Crop Top",
      category: "SetPants",
      image: "https://m.media-amazon.com/images/I/61v-w9NSpwL._UL1500_.jpg",
      price: 399,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Chokhi Bandhni Women's Rayon Embroidered Regular Fit Top",
      category: "Tops",
      image: "https://m.media-amazon.com/images/I/81IXcxbU9TL._UL1500_.jpg",
      price: 369,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "ANNI DESIGNER Raniyal Georgette Saree with Blouse Piece",
      category: "Saree",
      image: "https://m.media-amazon.com/images/I/711+C0DBS5L._UL1447_.jpg" ,
      price: 269,
      brand: "Anni",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
        _id: "7",
        name: " Kuvarba Fashion Women's Banarasi Silk Saree With Unstiched Blouse Piece",
        category: "Saree",
        image: "https://m.media-amazon.com/images/I/71IszooqopL._UL1500_.jpg" ,
        price: 399,
        brand: "ANNI",
        rating: 4.5,
        numReviews: 15,
        description: "high quality product",
      },
      {
        _id: "8",
        name: "Women's Rayon Pant Loose fit Palazzos Combo (Red and White, Free Size)",
        category: "Pant",
        image: " https://m.media-amazon.com/images/I/61nuFtUs8lL._UL1500_.jpg",
        price: 289,
        brand: "Nike",
        rating: 4.5,
        numReviews: 25,
        description: "high quality product",
      },
      {
        _id: "9",
        name: "The Souled Store Women Tie Dye: Black Storm Multicolored Printed Hoodies",
        category: "Hoods",
        image: "https://m.media-amazon.com/images/I/61IAYIj91FL._UL1440_.jpg" ,
        price: 1219,
        brand: "Puma",
        rating: 4,
        numReviews: 15,
        description: "high quality product",
      },
      {
        _id: "6",
        name: "Women's Rayon Anarkali Kurta",
        category: "Kurta",
        image: "https://m.media-amazon.com/images/I/41+TQ7H19TL.jpg" ,
        price: 280 - 849,
        brand: "JUNEBEERY",
        rating: 4.5,
        numReviews: 15,
        description: "high quality product",
      },
  ],
};
export default data;
